Repository databrickslabs/overwatch, pull requests merged in 2022-12, with the labels that each got.

#656 Docs Restructure for 0701
  docs-compose/overwatch_docs/.hugo_build.lock
  docs-compose/overwatch_docs/content/DataEngineer/AdvancedTopics.md
  docs-compose/overwatch_docs/content/DataEngineer/Modules.md
  docs-compose/overwatch_docs/content/DataEngineer/Pipeline_Management.md
  docs-compose/overwatch_docs/content/DataEngineer/Productionizing.md
  docs-compose/overwatch_docs/content/DataEngineer/Upgrade.md
  docs-compose/overwatch_docs/content/DeployOverwatch/CloudInfra/AWS.md
  docs-compose/overwatch_docs/content/DeployOverwatch/CloudInfra/Azure.md
  docs-compose/overwatch_docs/content/DeployOverwatch/CloudInfra/_index.md
  docs-compose/overwatch_docs/content/DeployOverwatch/ConfigureOverwatch/Configuration.md
  docs-compose/overwatch_docs/content/DeployOverwatch/ConfigureOverwatch/ConfigurationLegacy.md
  docs-compose/overwatch_docs/content/DeployOverwatch/ConfigureOverwatch/Validation.md
  docs-compose/overwatch_docs/content/DeployOverwatch/ConfigureOverwatch/_index.md
  docs-compose/overwatch_docs/content/DeployOverwatch/RunningOverwatch/Job.md
  docs-compose/overwatch_docs/content/DeployOverwatch/RunningOverwatch/JobLegacy.md
  docs-compose/overwatch_docs/content/DeployOverwatch/RunningOverwatch/Notebook.md
  docs-compose/overwatch_docs/content/DeployOverwatch/RunningOverwatch/NotebookLegacy.md
  docs-compose/overwatch_docs/content/DeployOverwatch/RunningOverwatch/_index.md
  docs-compose/overwatch_docs/content/DeployOverwatch/_index.md
  docs-compose/overwatch_docs/content/Developer_Docs/Audit.md
  docs-compose/overwatch_docs/content/Developer_Docs/Cluster Events.md
  docs-compose/overwatch_docs/content/Developer_Docs/Clusters.md
  docs-compose/overwatch_docs/content/Developer_Docs/Error Handling.md
  docs-compose/overwatch_docs/content/Developer_Docs/Jobs.md
  docs-compose/overwatch_docs/content/Developer_Docs/Resuming.md
  docs-compose/overwatch_docs/content/Developer_Docs/Spark Events.md
  docs-compose/overwatch_docs/content/Developer_Docs/_index.md
  docs-compose/overwatch_docs/content/Developer_Docs/accounts.md
  docs-compose/overwatch_docs/content/Developer_Docs/notebooks.md
  docs-compose/overwatch_docs/content/EnvironmentSetup/_index.md
  docs-compose/overwatch_docs/content/GettingStarted/Roadmap.md
  docs-compose/overwatch_docs/content/GettingStarted/Troubleshooting.md
Labels: documentation

#563 270 multiworkspace deployment
  src/main/scala/com/databricks/labs/overwatch/ApiCallV2.scala
  src/main/scala/com/databricks/labs/overwatch/ApiMeta.scala
  src/main/scala/com/databricks/labs/overwatch/MultiWorkspaceDeployment.scala
  src/main/scala/com/databricks/labs/overwatch/MultiWorkspaceRunner.scala
  src/main/scala/com/databricks/labs/overwatch/env/Database.scala
  src/main/scala/com/databricks/labs/overwatch/env/Workspace.scala
  src/main/scala/com/databricks/labs/overwatch/pipeline/Bronze.scala
  src/main/scala/com/databricks/labs/overwatch/pipeline/BronzeTransforms.scala
  src/main/scala/com/databricks/labs/overwatch/pipeline/Initializer.scala
  src/main/scala/com/databricks/labs/overwatch/pipeline/Module.scala
  src/main/scala/com/databricks/labs/overwatch/pipeline/Pipeline.scala
  src/main/scala/com/databricks/labs/overwatch/pipeline/PipelineTable.scala
  src/main/scala/com/databricks/labs/overwatch/pipeline/Schema.scala
  src/main/scala/com/databricks/labs/overwatch/pipeline/Silver.scala
  src/main/scala/com/databricks/labs/overwatch/utils/Config.scala
  src/main/scala/com/databricks/labs/overwatch/utils/SparkSessionWrapper.scala
  src/main/scala/com/databricks/labs/overwatch/utils/Structures.scala
  src/main/scala/com/databricks/labs/overwatch/validation/DeploymentValidation.scala
  src/test/scala/com/databricks/labs/overwatch/ApiCallV2Test.scala
  src/test/scala/com/databricks/labs/overwatch/ParamDeserializerTest.scala
  terraform/azure/overwatch-azure.scala
Labels: enhancement

#626 APIv2 code change
  src/main/scala/com/databricks/labs/overwatch/ApiCallV2.scala
  src/main/scala/com/databricks/labs/overwatch/ApiMeta.scala
Labels: bug

#605 Validate Register Remote Overwatch
  src/main/scala/com/databricks/labs/overwatch/env/Workspace.scala
  src/main/scala/com/databricks/labs/overwatch/pipeline/Bronze.scala
  src/main/scala/com/databricks/labs/overwatch/pipeline/Gold.scala
  src/main/scala/com/databricks/labs/overwatch/pipeline/Pipeline.scala
  src/main/scala/com/databricks/labs/overwatch/pipeline/PipelineView.scala
  src/main/scala/com/databricks/labs/overwatch/utils/Tools.scala
Labels: enhancement
