Repository databrickslabs/overwatch, pull requests merged in 2022-11, with the labels that each got.

#620 619 -- clusterSpec from pools optimization
  src/main/scala/com/databricks/labs/overwatch/pipeline/SilverTransforms.scala
Labels: optimization

#602 07003 patch
  build.sbt
  src/main/scala/com/databricks/labs/overwatch/pipeline/BronzeTransforms.scala
  src/main/scala/com/databricks/labs/overwatch/pipeline/GoldTransforms.scala
  src/main/scala/com/databricks/labs/overwatch/pipeline/PipelineFunctions.scala
  src/main/scala/com/databricks/labs/overwatch/pipeline/SilverTransforms.scala
  src/main/scala/com/databricks/labs/overwatch/utils/Upgrade.scala
Labels: bug

#616 adding sqlHistory Module in the dependency table
  docs-compose/overwatch_docs/content/DataEngineer/Pipeline_Management.md
  docs/404.html
  docs/categories/index.html
  docs/changelog/index.html
  docs/contributing/index.html
  docs/dataengineer/definitions/061x/index.html
  docs/dataengineer/definitions/index.html
  docs/dataengineer/index.html
  docs/dataengineer/pipeline_management/index.html
  docs/dataengineer/productionizing/index.html
  docs/dataengineer/upgrade/index.html
  docs/environmentsetup/aws/index.html
  docs/environmentsetup/azure/index.html
  docs/environmentsetup/index.html
  docs/faq/index.html
  docs/gettingstarted/advancedtopics/index.html
  docs/gettingstarted/configuration/index.html
  docs/gettingstarted/index.html
  docs/gettingstarted/modules/index.html
  docs/index.html
  docs/tags/index.html
Labels: documentation

#634 632_ClusterbronzeFix
  src/main/scala/com/databricks/labs/overwatch/pipeline/BronzeTransforms.scala
Labels: bug
