Repository databrickslabs/overwatch, pull requests merged in 2023-08, with the labels that each got.

#918 [FEAT] - ETL_DataPathPrefix_Migration
  src/main/scala/com/databricks/labs/overwatch/MultiWorkspaceDeployment.scala
  src/main/scala/com/databricks/labs/overwatch/env/Database.scala
  src/main/scala/com/databricks/labs/overwatch/env/Workspace.scala
  src/main/scala/com/databricks/labs/overwatch/pipeline/Bronze.scala
  src/main/scala/com/databricks/labs/overwatch/pipeline/Migration.scala
  src/main/scala/com/databricks/labs/overwatch/pipeline/MigrationRunner.scala
  src/main/scala/com/databricks/labs/overwatch/pipeline/Restore.scala
  src/main/scala/com/databricks/labs/overwatch/pipeline/RestoreRunner.scala
  src/main/scala/com/databricks/labs/overwatch/pipeline/Snapshot.scala
  src/main/scala/com/databricks/labs/overwatch/pipeline/SnapshotRunner.scala
  src/main/scala/com/databricks/labs/overwatch/utils/Structures.scala
  src/main/scala/com/databricks/labs/overwatch/utils/Tools.scala
Labels: enhancement

#1022 code fix
  src/main/scala/com/databricks/labs/overwatch/pipeline/BronzeTransforms.scala
Labels: bug

#982 Update_Azure_gcp_instances
  src/main/resources/Azure_Instance_Details.csv
  src/main/resources/Gcp_Instance_Details.csv
  src/main/scala/com/databricks/labs/overwatch/utils/Tools.scala
Labels: enhancement

#674 462 dbsql warehouse
  src/main/scala/com/databricks/labs/overwatch/api/ApiMeta.scala
  src/main/scala/com/databricks/labs/overwatch/env/Workspace.scala
  src/main/scala/com/databricks/labs/overwatch/pipeline/Bronze.scala
  src/main/scala/com/databricks/labs/overwatch/pipeline/BronzeTransforms.scala
  src/main/scala/com/databricks/labs/overwatch/pipeline/DbsqlTransforms.scala
  src/main/scala/com/databricks/labs/overwatch/pipeline/Gold.scala
  src/main/scala/com/databricks/labs/overwatch/pipeline/GoldTransforms.scala
  src/main/scala/com/databricks/labs/overwatch/pipeline/PipelineFunctions.scala
  src/main/scala/com/databricks/labs/overwatch/pipeline/PipelineTargets.scala
  src/main/scala/com/databricks/labs/overwatch/pipeline/Schema.scala
  src/main/scala/com/databricks/labs/overwatch/pipeline/Silver.scala
  src/main/scala/com/databricks/labs/overwatch/pipeline/SilverTransforms.scala
  src/test/scala/com/databricks/labs/overwatch/utils/StringExtTest.scala
Labels: enhancement

#989 Issue 928. Correct the cluster_type captured
  src/main/scala/com/databricks/labs/overwatch/pipeline/WorkflowsTransforms.scala
Labels: bug

#945 [DOCS] - 910 add pipReport and pipeline_report structure in docs
  docs-compose/overwatch_docs/content/DataEngineer/Definitions/_index.md
  docs-compose/overwatch_docs/content/DataEngineer/Pipeline_Management.md
  docs/assets/TableSamples/pipreport.tab
Labels: documentation

#1016 resolving bug in StructToMap
  src/main/scala/com/databricks/labs/overwatch/utils/SchemaTools.scala
  src/test/scala/com/databricks/labs/overwatch/utils/SchemaToolsTest.scala
Labels: bug

#977 [Doc] - ETLDataPrefix - Migration / Merge Process
  docs-compose/overwatch_docs/content/DataEngineer/Productionizing.md
  docs-compose/overwatch_docs/static/images/DataEngineer/Migration_Job.png
  docs-compose/overwatch_docs/static/images/DataEngineer/Migration_path.png
  docs-compose/overwatch_docs/static/images/DataEngineer/clone_report.png
  docs-compose/overwatch_docs/static/images/DataEngineer/restore_job.png
  docs-compose/overwatch_docs/static/images/DataEngineer/restore_path.png
  docs-compose/overwatch_docs/static/images/DataEngineer/snapshotTarget.png
  docs-compose/overwatch_docs/static/images/DataEngineer/snapshotTarget_Data.png
  docs-compose/overwatch_docs/static/images/DataEngineer/snapshot_job.png
Labels: documentation

#917 [FEAT] - Verbose audit logging 721
  src/main/scala/com/databricks/labs/overwatch/pipeline/Gold.scala
  src/main/scala/com/databricks/labs/overwatch/pipeline/GoldTransforms.scala
  src/main/scala/com/databricks/labs/overwatch/pipeline/PipelineFunctions.scala
  src/main/scala/com/databricks/labs/overwatch/pipeline/PipelineTargets.scala
  src/main/scala/com/databricks/labs/overwatch/pipeline/Schema.scala
Labels: enhancement
