Repository databrickslabs/overwatch, pull requests merged in 2023-04, with the labels that each got.

#842 api namespace change
  src/main/scala/com/databricks/labs/overwatch/api/ApiCall.scala
  src/main/scala/com/databricks/labs/overwatch/api/ApiCallV2.scala
  src/main/scala/com/databricks/labs/overwatch/api/ApiMeta.scala
  src/main/scala/com/databricks/labs/overwatch/env/Workspace.scala
  src/main/scala/com/databricks/labs/overwatch/pipeline/BronzeTransforms.scala
  src/main/scala/com/databricks/labs/overwatch/validation/DeploymentValidation.scala
  src/test/scala/com/databricks/labs/overwatch/ApiCallV2Test.scala
Labels: enhancement

#859 getParams implemented
  src/main/scala/com/databricks/labs/overwatch/MultiWorkspaceDeployment.scala
Labels: enhancement

#825 Slash Management
  src/main/scala/com/databricks/labs/overwatch/MultiWorkspaceDeployment.scala
  src/main/scala/com/databricks/labs/overwatch/pipeline/BronzeTransforms.scala
  src/main/scala/com/databricks/labs/overwatch/utils/Tools.scala
  src/test/scala/com/databricks/labs/overwatch/utils/HelpersTest.scala
Labels: enhancement

#860 Added Logic to create PipReport
  src/main/scala/com/databricks/labs/overwatch/utils/Tools.scala
Labels: enhancement

#876 Update azure/aws_instance_details.csv
  src/main/resources/AWS_Instance_Details.csv
  src/main/resources/Azure_Instance_Details.csv
Labels: data quality

#872 AAD authentication for EventHubs implemented for MWS
  src/main/scala/com/databricks/labs/overwatch/MultiWorkspaceDeployment.scala
  src/main/scala/com/databricks/labs/overwatch/pipeline/Schema.scala
  src/main/scala/com/databricks/labs/overwatch/utils/Structures.scala
  src/main/scala/com/databricks/labs/overwatch/validation/DeploymentValidation.scala
Labels: enhancement

#875 Add documentation for Dtabase name in config
  docs-compose/overwatch_docs/content/DeployOverwatch/ConfigureOverwatch/Configuration.md
Labels: documentation

#870 Document for Wrong dbu calculation for worker node for long running cluster
  docs-compose/overwatch_docs/content/DataEngineer/Definitions/_index.md
Labels: documentation

#880 GCP documentation added
  docs-compose/overwatch_docs/content/DeployOverwatch/CloudInfra/AWS.md
  docs-compose/overwatch_docs/content/DeployOverwatch/CloudInfra/_index.md
  docs-compose/overwatch_docs/content/DeployOverwatch/ConfigureOverwatch/ConfigFileList.md
  docs-compose/overwatch_docs/content/DeployOverwatch/ConfigureOverwatch/Configuration.md
  docs-compose/overwatch_docs/content/DeployOverwatch/ConfigureOverwatch/SecurityConsiderations.md
  docs-compose/overwatch_docs/content/DeployOverwatch/ConfigureOverwatch/Validation.md
  docs-compose/overwatch_docs/static/assets/DeployOverwatch/072x_overwatch_deployment_config_template.csv
  docs-compose/overwatch_docs/static/assets/DeployOverwatch/072x_overwatch_deployment_config_template.xlsx
Labels: documentation

#884 UC Enablement docs
  docs-compose/overwatch_docs/.hugo_build.lock
  docs-compose/overwatch_docs/content/DeployOverwatch/ConfigureOverwatch/ConfigDetailsByVersion.md
  docs-compose/overwatch_docs/content/DeployOverwatch/UCEDeployment/CloudStorageAccessRequirements/AWS.md
  docs-compose/overwatch_docs/content/DeployOverwatch/UCEDeployment/CloudStorageAccessRequirements/Azure.md
  docs-compose/overwatch_docs/content/DeployOverwatch/UCEDeployment/CloudStorageAccessRequirements/GCP.md
  docs-compose/overwatch_docs/content/DeployOverwatch/UCEDeployment/CloudStorageAccessRequirements/_index.md
  docs-compose/overwatch_docs/content/DeployOverwatch/UCEDeployment/MigratingToUC.md
  docs-compose/overwatch_docs/content/DeployOverwatch/UCEDeployment/UCEConfiguration.md
  docs-compose/overwatch_docs/content/DeployOverwatch/UCEDeployment/UCEPreReqs.md
  docs-compose/overwatch_docs/content/DeployOverwatch/UCEDeployment/_index.md
  docs-compose/overwatch_docs/content/DeployOverwatch/_index.md
  docs-compose/overwatch_docs/static/assets/DeployOverwatch/072x_overwatch_deployment_config_template.csv
  docs-compose/overwatch_docs/static/assets/DeployOverwatch/072x_overwatch_deployment_config_template.xlsx
  docs-compose/overwatch_docs/static/assets/DeployOverwatch/UC_Migration_Utility-Hive_metastore_To_Unity_Catalog.dbc
  docs-compose/overwatch_docs/static/assets/DeployOverwatch/UC_Migration_Utility-Hive_metastore_To_Unity_Catalog.html
Labels: documentation

#889 Instance Details Resource File Type fixes
  src/main/resources/AWS_Instance_Details.csv
  src/main/resources/Gcp_Instance_Details.csv
Labels: enhancement
