Repository databrickslabs/overwatch, pull requests merged in 2023-03, with the labels that each got.

#793 Change Validate for MWS logic
  src/main/scala/com/databricks/labs/overwatch/MultiWorkspaceDeployment.scala
  src/main/scala/com/databricks/labs/overwatch/validation/DeploymentValidation.scala
Labels: bug

#792 709 incorrect job trigger
  src/main/scala/com/databricks/labs/overwatch/pipeline/WorkflowsTransforms.scala
Labels: enhancement

#786 gcp integration added
  src/main/resources/Gcp_Instance_Details.csv
  src/main/scala/com/databricks/labs/overwatch/MultiWorkspaceDeployment.scala
  src/main/scala/com/databricks/labs/overwatch/pipeline/BronzeTransforms.scala
  src/main/scala/com/databricks/labs/overwatch/pipeline/GoldTransforms.scala
  src/main/scala/com/databricks/labs/overwatch/pipeline/InitializerFunctions.scala
  src/main/scala/com/databricks/labs/overwatch/pipeline/Pipeline.scala
  src/main/scala/com/databricks/labs/overwatch/pipeline/PipelineFunctions.scala
  src/main/scala/com/databricks/labs/overwatch/pipeline/Schema.scala
  src/main/scala/com/databricks/labs/overwatch/pipeline/SilverTransforms.scala
  src/main/scala/com/databricks/labs/overwatch/utils/Config.scala
  src/main/scala/com/databricks/labs/overwatch/validation/DeploymentValidation.scala
Labels: gcp

#807 auditlogprefix_source_aws changed to auditlogprefix_source_path
  src/main/scala/com/databricks/labs/overwatch/MultiWorkspaceDeployment.scala
  src/main/scala/com/databricks/labs/overwatch/pipeline/Schema.scala
  src/main/scala/com/databricks/labs/overwatch/utils/Structures.scala
  src/main/scala/com/databricks/labs/overwatch/validation/DeploymentValidation.scala
Labels: gcp

#818 Change task_runtime.startTS anchor to startTime instead of submissionTime
  src/main/scala/com/databricks/labs/overwatch/pipeline/WorkflowsTransforms.scala
Labels: bug

#826 changing code to derive cloud type
  src/main/scala/com/databricks/labs/overwatch/utils/Config.scala
Labels: bug

#841 temp_dir for MSW deployment added
  src/main/scala/com/databricks/labs/overwatch/MultiWorkspaceDeployment.scala
  src/main/scala/com/databricks/labs/overwatch/pipeline/Schema.scala
  src/main/scala/com/databricks/labs/overwatch/utils/Structures.scala
Labels: enhancement

#848 handled class not found
  src/main/scala/com/databricks/labs/overwatch/MultiWorkspaceDeployment.scala
  src/main/scala/com/databricks/labs/overwatch/pipeline/BronzeTransforms.scala
  src/main/scala/com/databricks/labs/overwatch/validation/DeploymentValidation.scala
Labels: bug

#844 Remove ClusterSpecDetailSilver Dependency from Cluster Gold
  src/main/scala/com/databricks/labs/overwatch/pipeline/Gold.scala
Labels: bug
