Repository databrickslabs/overwatch, pull requests merged in 2024-06, with the labels that each got.

#1232 adding fix for schemaScrubber
  src/main/scala/com/databricks/labs/overwatch/utils/SchemaScrubber.scala
  src/test/scala/com/databricks/labs/overwatch/utils/SchemaToolsTest.scala
Labels: bug, enhancement

#1236 fix for null driver_type_id and node_type_id in jrcp
  src/main/scala/com/databricks/labs/overwatch/pipeline/WorkflowsTransforms.scala
Labels: bug

#1234 Modify Cluster_snapshot_bronze column
  src/main/scala/com/databricks/labs/overwatch/pipeline/BronzeTransforms.scala
Labels: bug

#1244 Update_gcp_instance_types
  src/main/resources/Gcp_Instance_Details.csv
Labels: data quality

#1246 Update_Azure_Instance_details
  src/main/resources/Azure_Instance_Details.csv
Labels: enhancement

#1248 Update_AWS_instance_types
  src/main/resources/AWS_Instance_Details.csv
  src/main/resources/Gcp_Instance_Details.csv
Labels: enhancement
