Repository databrickslabs/overwatch, pull requests merged in 2024-08, with the labels that each got.

#1071 1030 pipeline validation framework
  src/main/scala/com/databricks/labs/overwatch/api/ApiMeta.scala
  src/main/scala/com/databricks/labs/overwatch/pipeline/BronzeTransforms.scala
  src/main/scala/com/databricks/labs/overwatch/pipeline/PipelineTable.scala
  src/main/scala/com/databricks/labs/overwatch/utils/PipelineValidationHelper.scala
  src/main/scala/com/databricks/labs/overwatch/utils/Structures.scala
  src/main/scala/com/databricks/labs/overwatch/validation/PipelineValidation.scala
Labels: enhancement

#1270 adding fix for duplicate accountId in module 2010 and 3019
  src/main/scala/com/databricks/labs/overwatch/pipeline/GoldTransforms.scala
  src/main/scala/com/databricks/labs/overwatch/pipeline/Schema.scala
  src/main/scala/com/databricks/labs/overwatch/pipeline/WorkflowsTransforms.scala
Labels: bug

#1254 1218 warehouse state details
  src/main/scala/com/databricks/labs/overwatch/MultiWorkspaceDeployment.scala
  src/main/scala/com/databricks/labs/overwatch/env/Workspace.scala
  src/main/scala/com/databricks/labs/overwatch/pipeline/Bronze.scala
  src/main/scala/com/databricks/labs/overwatch/pipeline/InitializerFunctions.scala
  src/main/scala/com/databricks/labs/overwatch/pipeline/PipelineTargets.scala
  src/main/scala/com/databricks/labs/overwatch/pipeline/Silver.scala
  src/main/scala/com/databricks/labs/overwatch/pipeline/SilverTransforms.scala
  src/main/scala/com/databricks/labs/overwatch/utils/Config.scala
  src/main/scala/com/databricks/labs/overwatch/utils/Structures.scala
Labels: enhancement

#1223 Add descriptive `NamedTransformation`s to Spark UI
  build.sbt
  src/main/scala/com/databricks/labs/overwatch/pipeline/ETLDefinition.scala
  src/main/scala/com/databricks/labs/overwatch/pipeline/SilverTransforms.scala
  src/main/scala/com/databricks/labs/overwatch/pipeline/WorkflowsTransforms.scala
  src/main/scala/com/databricks/labs/overwatch/utils/TransformationDescriber.scala
  src/test/scala/com/databricks/labs/overwatch/utils/TransformationDescriberTest.scala
Labels: enhancement, Testing

#1265 adding code for warehouseStateFact gold
  src/main/resources/Warehouse_DBU_Details.csv
  src/main/scala/com/databricks/labs/overwatch/pipeline/Gold.scala
  src/main/scala/com/databricks/labs/overwatch/pipeline/GoldTransforms.scala
  src/main/scala/com/databricks/labs/overwatch/pipeline/Pipeline.scala
  src/main/scala/com/databricks/labs/overwatch/pipeline/PipelineTargets.scala
  src/main/scala/com/databricks/labs/overwatch/pipeline/Schema.scala
  src/main/scala/com/databricks/labs/overwatch/pipeline/SilverTransforms.scala
Labels: enhancement
