Repository databrickslabs/overwatch, pull requests merged in 2024-01, with the labels that each got.

#1120 code missed in merge
  src/main/scala/com/databricks/labs/overwatch/env/Workspace.scala
Labels: enhancement

#1121 silver warehouse spec fix
  src/main/scala/com/databricks/labs/overwatch/pipeline/DbsqlTransforms.scala
  src/main/scala/com/databricks/labs/overwatch/pipeline/SilverTransforms.scala
Labels: bug

#1116 implemented recon
  src/main/scala/com/databricks/labs/overwatch/pipeline/PipelineTable.scala
  src/main/scala/com/databricks/labs/overwatch/pipeline/PipelineTargets.scala
  src/main/scala/com/databricks/labs/overwatch/utils/Structures.scala
  src/main/scala/com/databricks/labs/overwatch/utils/Tools.scala
  src/main/scala/com/databricks/labs/overwatch/validation/DataReconciliation.scala
Labels: enhancement

#1124 1123 add shufflefactor to notebookcommands module
  src/main/scala/com/databricks/labs/overwatch/pipeline/Gold.scala
Labels: enhancement

#1130 891 traceability disable
  src/main/scala/com/databricks/labs/overwatch/api/ApiCallV2.scala
  src/main/scala/com/databricks/labs/overwatch/pipeline/Module.scala
Labels: enhancement

#1134 corner case commit
  src/main/scala/com/databricks/labs/overwatch/pipeline/BronzeTransforms.scala
Labels: enhancement

#1135 Handle CLSD Cluster Impute when jrcp and clusterSpec is Empty
  src/main/scala/com/databricks/labs/overwatch/pipeline/SilverTransforms.scala
Labels: bug

#1136 Exclude 2011 and 2014 as dependency module for 2019
  src/main/scala/com/databricks/labs/overwatch/pipeline/Silver.scala
  src/main/scala/com/databricks/labs/overwatch/pipeline/SilverTransforms.scala
Labels: bug

#1137 891 trace fix
  src/main/scala/com/databricks/labs/overwatch/pipeline/Module.scala
Labels: enhancement

#1126 1115 doc add limitation for fleet instance in overwatch doc
  docs-compose/overwatch_docs/content/DataEngineer/Definitions/_index.md
Labels: documentation

#1140 adding fix for empty EH config for system tables
  src/main/scala/com/databricks/labs/overwatch/validation/DeploymentValidation.scala
Labels: bug

#1142 corner case commit for job runs
  src/main/scala/com/databricks/labs/overwatch/env/Workspace.scala
Labels: bug

#1141 adding fix for empty audit log for warehouse_spec_silver
  src/main/scala/com/databricks/labs/overwatch/pipeline/DbsqlTransforms.scala
Labels: bug

#1143 recon columns removed
  src/main/scala/com/databricks/labs/overwatch/pipeline/PipelineTargets.scala
Labels: data quality
