Repository databrickslabs/overwatch, pull requests merged in 2024-05, with the labels that each got.

#1128 Docs added for traceability
  docs-compose/overwatch_docs/content/DataEngineer/AdvancedTopics.md
Labels: documentation

#1213 Convert spec.custom_tags from struct type to map type
  src/main/scala/com/databricks/labs/overwatch/pipeline/BronzeTransforms.scala
Labels: bug

#1197 Sql endpoint validation
  src/main/scala/com/databricks/labs/overwatch/validation/DeploymentValidation.scala
Labels: enhancement
